### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by dwc05101** [Ssnnaaiill/subway#1]
![스크린샷 2019-11-18 오전 11 05 19](https://user-images.githubusercontent.com/43431790/69019345-91709980-09f3-11ea-9ecb-ff2ef2cc012c.png)

아직 미완성인 걸로 알겠습니다.

![스크린샷 2019-11-18 오전 11 05 49](https://user-images.githubusercontent.com/43431790/69019354-99c8d480-09f3-11ea-86ee-95a625eaeb6c.png)

마커를 만드는 건 initLayer안에 넣거나, Dynamic하게 생성할 경우에는 따로 method로 빼놓는 게 좋을 것 같습니
다.

그외의 코드 구조는 가장 깔끔하네요. Vuex를 활용해보려는 시도도 좋았습니다. 추후 과업에 분명히 도움이 될거에요.

+ 저번에 말했던 views와 components를 이용해서 보여지는 영역과 그 안을 구성하는 요소를 구분해서 개발해보는걸 추천합니다.

**Comment by Ssnnaaiill** [comment]
- 마커 생성하는 부분은 `initMarkers` 라는 method로 따로 빼주었습니다.
- Marker clustering 기능 구현하였습니다.
  - map 확대를 하지 않은 상태에서도 마커들이 사라지지 않고 group에도 들어가지 않는 경우가 있습니다. 가까운 지역이 인식되지 않아 생겨나는 문제인 것으로 추정되며, 여러 번 확대했다 줄였다를 반복하면 이탈된 마커들이 그룹 안으로 들어가집니다.
- Vuex 사용하여 지정한 지하철 역으로 map 이동시키는 기능 구현하였습니다.
- Vue-router를 사용하여 view / component 구분해주었습니다.

**Comment by dwc05101** [comment]
LGTM. 전체적으로 깔끔하네요. 잘했습니다.

다만 flyTo는 상당히 무거운 transition effect를 제공합니다. 효과는 화려하지만, 되려 끊겨 보이는 경우가 종종 발생합니다. 그래서 왠만하면 setView를 사용하는게 좋을 듯 합니다.

**Comment by dwc05101** [comment]
![스크린샷 2019-11-19 오전 10 25 34](https://user-images.githubusercontent.com/43431790/69108091-f80abb80-0ab6-11ea-9cb8-96952efc0f18.png)

원래있던 코드를 어느정도 벤치마킹하는건 좋지만, 따라하더라도 제가 한 실수를 그대로 따라하면 안돼요ㅋㅋㅋㅋ
flex : 1 만 있어도 됩니다. 각 코드를 왜 사용하는지 이해했길 바랍니다.

**Comment by Ssnnaaiill** [comment]
comment 달아주신 부분들 수정했습니다. 감사합니다.
 
![jjgd](https://user-images.githubusercontent.com/29303443/69110228-62265f00-0abd-11ea-93ef-246713d84828.PNG)
추가적으로 3호선 교대역의 위치가 어째서인지 전주쯤으로 표시됩니다. 해당 역의 위도, 경도에 대한 데이터가 잘못 들어간 것이 원인인 것 같습니다. 일단은 구글 지도에서 3호선 교대역의 위치를 찾아 json 파일의 위/경도 데이터를 수정하였습니다.
